### ISSUE TITLE
Koodikatselmointi 28.12

### ISSUE THREAD

**Issue by ptimonen** [Melchan/shakkiPeliJoulu#1]
Koodi ladattu klo 23:05

-Luokat on jaettu selkeästi paketteihin, mikä tekee lukemisesta helppoa

-Koodi on jaettu järkevästi eri luokkiin, joista jokaisella on yksi vastuu

-Yksikkötestit ovat kattavuudeltaan erinomaiset, mutta etenking KingRulesTest.java sisältää paljon copy-pastea, joka voisi hyötyä muutamasta apufunktiosta.

-Taikanumeroiden korvaaminen paketissa ChessBoard nimetyillä vaikioilla tekisi lukemisesta helpompaa. 

-Luokkakaaviossa ChessBoardInitializer sisältää ChessPiecet (eikä pelilauta), ja ChessBoardInitializer sisältää Gamen, mikä vaikuttaa oudolta. Koodin rakenteessa tätä ongelmaa ei kuitenkaan ole.

**Comment by ajkieloaho** [comment]
Ladattu 6.1.2016 17:12

- Testejä on paljon ja niitä on kattavasti. Selkeästi olet pystynyt noudattamaan projektissa tdd-oppeja.
- Koodi on selkeää ja helposti luettavaa. Se on jaettu selkeästi omiin kokonaisuuksiksi.
- Luokat ovat loogisesti jaettu ja luokkissa on mietitty metodien näkyvyyttä ja noudattavat metodeineen yhden toiminnallisuuden periaatetta. 
- Enumeita on käytetty kiitettävästi primitiivien sijasta.
- Jokaisessa projektissa on omat ongelmat ja tässä näyttää olevan sisäkkäisien if-blokkien suuri määrä. Olen ymmärtänyt, ne että ovat virhealttiita ja niitä tulisi pyrkiä siksi välttämään, mutta niiden käyttöä ei välttämättä peleissä pysty estämään.
- Hienon näköinen on ainakin GUI! Toivottavasti saat kaiken valmiiksi, koska vaikuttaa suuritöiseltä työltä.
